# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-16 04:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20171115_1204'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Request',
            new_name='Requests',
        ),
    ]
