# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-16 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20171116_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
