# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-28 05:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20171116_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='product',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='catalog.Product'),
        ),
    ]
